server:
    port: 9100

spring:
  data:
    cassandra:
      cluster-name: "TechLabCassandraCluster"
      contact-points: 10.45.250.112,10.45.250.113,10.45.250.114
      port: 9042
      #keyspace-name: cdc
      keyspace-name: testKeySpace
      username: ${login:}
      password: ${pass:}

app:
  config:
    id: 1